version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: parcel-carrier-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: parcel-carrier-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - parcel-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: parcel-carrier-app
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # On utilise l'URI pour passer l'authentification et le authSource=admin
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongodb:27017/parcel-carrier-mongodb?authSource=admin
      - JWT_SECRET=VotreCleSecrete123456789VotreCleSecreteSuper789AMinChanger
    ports:
      - "8080:8080"
    networks:
      - parcel-network

  mongo-express:
    image: mongo-express:latest
    container_name: parcel-carrier-mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
    ports:
      - "8081:8081"
    networks:
      - parcel-network

volumes:
  mongodb_data:
  n8n_data:

networks:
  parcel-network:
    driver: bridge
